export const Data = [
  {
    id: 1,
    image: "Images/fish_teriyaki.jpg",
    name: "Fish Teriyaki",
    category: "Dinner",
    price: "₹670",
    description: "lorem25",
  },
  {
    id: 2,
    image: "Images/burger.jpg",
    name: "Mac Burger",
    category: "Evening",
    price: "₹150",
    description: "lorem25",
  },
  {
    id: 3,
    image: "Images/chocklet_icecream.jpg",
    name: "Chocolate Icecream",
    category: "Dinner",
    price: "₹550",
    description: "lorem25",
  },
  {
    id: 4,
    image: "/Images/chowmeen.jpg",
    name: "Chowmeen",
    category: "Evening",
    price: "₹110",
    description: "lorem25",
  },
  {
    id: 5,
    image: "Images/coffee.jpg",
    name: "Coffee",
    category: "Evening",
    price: "₹190",
    description: "lorem25",
  },
  {
    id: 6,
    image: "Images/cookie.jpg",
    name: "Cookie",
    category: "Evening",
    price: "₹100",
    description: "lorem25",
  },
  {
    id: 7,
    image: "Images/baked_eggs.jpg",
    name: "Baked Eggs",
    category: "Breakfast",
    price: "₹120",
    description: "lorem25",
  },

  {
    id: 8,
    image: "Images/grilled_fish.jpg",
    name: "Grilled Fish",
    category: "Dinner",
    price: "₹710",
    description: "lorem25",
  },
  {
    id: 9,
    image: "Images/honey_cookie.jpg",
    name: "Honey Cookkie",
    category: "Evening",
    price: "₹150",
    description: "lorem25",
  },
  {
    id: 10,
    image: "Images/mix_salad.jpg",
    name: "Salad",
    category: "Breakfast",
    price: "₹199",
    description: "lorem25",
  },
  {
    id: 11,
    image: "Images/non_veg_burger.jpg",
    name: "Chicken Burger",
    category: "Evening",
    price: "₹260",
    description: "lorem25",
  },
  {
    id: 12,
    image: "Images/orange_ice.jpg",
    name: "Orange Ice",
    category: "Drinks",
    price: "₹90",
    description: "lorem25",
  },
  {
    id: 13,
    image: "Images/rice_bowls.jpg",
    name: "Rice Bowls",
    category: "Breakfast",
    price: "₹330",
    description: "lorem25",
  },
  {
    id: 14,
    image: "Images/sandwich.jpg",
    name: "Fruit Sandwich",
    category: "Breakfast",
    price: "₹210",
    description: "lorem25",
  },
  {
    id: 15,
    image: "Images/seafood.jpg",
    name: "Italian Pasta",
    category: "Breakfast",
    price: "₹190",
    description: "lorem25",
  },
  {
    id: 16,
    image: "Images/salad.jpg",
    name: "Mix Salad",
    category: "Breakfast",
    price: "₹315",
    description: "lorem25",
  },
  {
    id: 17,
    image: "Images/turkish_mussels.jpg",
    name: "Turkish Mussels",
    category: "Evening",
    price: "₹180",
    description: "lorem25",
  },
  {
    id: 18,
    image: "Images/beer.jpg",
    name: "Beer",
    category: "Drinks",
    price: "₹160",
    description: "lorem25",
  },
];
